module.exports = {
    clearMocks: true,
    rootDir: '.',
    moduleNameMapper: {
        '@auth/(.*)': '<rootDir>/auth/$1',
        '@errors/(.*)': '<rootDir>/errorHandling/$1',
        '@log/(.*)': '<rootDir>/logging/$1',
        '@root/(.*)': '<rootDir>/$1',
        '@routes/(.*)': '<rootDir>/endpoints/$1',
        '@utils/(.*)': '<rootDir>/utils/$1',
        '@tests/(.*)': "'<rootDir>/tests/$1",
        '@queries/(.*)': "'<rootDir>/queries/$1",
    },
    collectCoverage: true,
    coverageDirectory: 'coverage',
    setupFilesAfterEnv: ['<rootDir>/tests/setup/singleton.js'],
    slowTestThreshold: 3,
    testPathIgnorePatterns: ['/node_modules/'],
    verbose: true,
};
